server:
    port: 9091
spring:
    application:
        name: clientService1
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.1.14:7071/eureka/
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign:
    hystrix:
        enabled: true
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false

---
spring:
    profiles: docker
eureka:
    instance:
        ip-address: "${host}"
        non-secure-port: "${port}"
        instance-id: "${host}:${port}"
        statusPageUrl: "http://${host}:${port}/info"
        healthCheckUrl: "http://${host}:${port}/health"
        homePageUrl: "http://${host}:${port}/"