server:
    port: 9091
spring:
    application:
        name: clientService1
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7071/eureka/
feign:
    hystrix:
        enabled: true
