server:
    port: 9999
spring:
    application:
        name: oauthservice
    jpa:
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        druid:
            driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: 127.0.0.1
        port: 6379
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7071/eureka/,http://localhost:7072/eureka/    
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
            
endpoints:
    health:
        sensitive: false
        enabled: true
management:
    security:
        enabled: false
security:
    basic:
        enabled: false
    oauth2:
        client:
            access-token-uri: http://localhost:9999/oauth/token
            user-authorization-uri: http://localhost:9999/oauth/authorize
        resource:
            user-info-uri:  http://localhost:9999/user
            prefer-token-info: false
            filter-order: 3
logging:
    config: classpath:logback.xml
    level:
        org.springframework: DEBUG
        org.springframework.web: DEBUG