server:
    port: 9092
spring:
    application:
        name: clientService2
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7072/eureka/
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}            
feign:
    hystrix:
        enabled: true
