server:
    port: 9092
spring:
    application:
        name: clientService2
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7072/eureka/
feign:
    hystrix:
        enabled: true
