spring:
    application:
        name: discovery-cluster
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://discovery1:7071/eureka/,http://discovery2:7072/eureka/
    server:
        enable-self-preservation: true
    instance:
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
    profiles: discovery1
server:
    port: 7071
eureka:
    instance:
        hostname: discovery1

---
spring:
    profiles: discovery2
server:
    port: 7072
eureka:
    instance:
        hostname: discovery2