spring:
    application:
        name: discovery-cluster
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://discovery1:7071/eureka/,http://discovery2:7072/eureka/
    server:
        enable-self-preservation: true
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}

---
spring:
    profiles: discovery1
server:
    port: 7071
    
---
spring:
    profiles: discovery2
server:
    port: 7072