server:
    port: 8083
    context-path: /ui
    session:
      cookie:
        name: aaaa
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#      client-authentication-scheme: query
#      authentication-scheme: query
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
spring:
  thymeleaf:
    cache: false

logging:
  level:
#    org: DEBUG
    org.springframework.security: DEBUG