server:
    port: 8888
spring:
    application:
        name: spring-cloud-zuul
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7072/eureka/
zuul:
    routes:
        api-a:
            path: /clientService2/**
            serviceId: clientService2
        api-b:
            path: /api-b/**
            serviceId: service-B
        api-a-url:
            path: /api-a-url/**
            url: http://localhost:2222/