server:
    port: 8888
spring:
    application:
        name: spring-cloud-zuul
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7072/eureka/
    instance:
        hostname: ${spring.cloud.client.ipAddress}
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
zuul:
    host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000
    routes:
        api-a:
            path: /clientService2/**
            serviceId: clientService2
        api-b:
            path: /api-b/**
            serviceId: service-B
        api-a-url:
            path: /api-a-url/**
            url: http://localhost:2222/
            
####超时配置####
ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
        enabled: true
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 600000
###超时配置###